// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ealk_q__sMXfg0-emuNfAkq0njaGrx0',
    appId: '1:491993932940:web:39a2946a7b9c0a0da107a9',
    messagingSenderId: '491993932940',
    projectId: 'jeetkjeo-a23d3',
    authDomain: 'jeetkjeo-a23d3.firebaseapp.com',
    storageBucket: 'jeetkjeo-a23d3.appspot.com',
    measurementId: 'G-V3GWQPK1TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU_szgIWYjHGBd8c3JLZ15fGEpNg8NXkc',
    appId: '1:491993932940:android:e7977f9f303a6b85a107a9',
    messagingSenderId: '491993932940',
    projectId: 'jeetkjeo-a23d3',
    storageBucket: 'jeetkjeo-a23d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-z3qdg5ubjtm4jyYnRz_ddoJM0Ytk4Y',
    appId: '1:491993932940:ios:8b37b65b578a6512a107a9',
    messagingSenderId: '491993932940',
    projectId: 'jeetkjeo-a23d3',
    storageBucket: 'jeetkjeo-a23d3.appspot.com',
    iosBundleId: 'com.codeneur.jeetKeJeo',
  );
}
